### Zarejestrowanie nowego uzytkownika
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "n2@gmail.com",
    "password": "123"
}

### Zaloguj sie jako istniejacy uzytkownik
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "n1@gmail.com",
    "password": "123"
}

### Test
GET http://localhost:3000/api/test