### Zarejestrowanie nowego uzytkownika
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "admin",
    "password": "123"
}

### Zaloguj sie jako istniejacy uzytkownik
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "admin",
    "password": "123"
}

### Wyloguj się
POST http://localhost:3000/api/auth/logout

### Pobierz dane o aktualnej sesji
GET http://localhost:3000/api/users/me

### Usuń sesje użytkownika o podanym emailu
PATCH http://localhost:3000/api/users/RemoveSessionByEmail
Content-Type: application/json

{
    "Email": "admin"
}
